/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gloria y Fátima
 */
import javax.swing.*; //Solo copiar lo que esta en rojo
import utilitarios.*;
import java.util.List;
import py.com.svma.bean.dto.ProductoDTO;
import py.com.svma.model.jdbc.ProductoDAO;
import py.com.svma.model.jdbc.ProductoDaoJDBC;
import java.sql.*;
import py.com.svma.model.jdbc.Conexion;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
       


public class VentanaPrincipalSVMA extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipalSVMA
     */
    data mostrar_datos;
    String set_look = "com.sun.java.swing.plaf.metal.MetalLookAndFeel";
   
    public VentanaPrincipalSVMA() {
        initComponents();
        this.setLocationRelativeTo(null);//Para centrar la interfaz gráfica
        mostrar_datos = new data();
      
        mostrar_datos.el_dato();//primero ejecutar este método para después ejecutar el resto
        lbl_data.setText("Hoy es "+mostrar_datos.dia_semana+ " "+mostrar_datos.dia+" de "+mostrar_datos.mes+" del año "+mostrar_datos.anho);
        timer1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        lbl_hora = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_producto = new javax.swing.JMenu();
        miten_registrar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miten_modificar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miten_eliminar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        miten_consultar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        miten_registrarCompra = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        miten_reporteCompra = new javax.swing.JMenuItem();
        miten_repProducto = new javax.swing.JMenuItem();
        menu_venta = new javax.swing.JMenu();
        miten_registrarVenta = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        miten_registrarCliente = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        miten_reporteVenta = new javax.swing.JMenuItem();
        menu_inventario = new javax.swing.JMenu();
        miten_revisar = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        miten_prepararPedido = new javax.swing.JMenuItem();
        menu_cuentacorriente = new javax.swing.JMenu();
        miten_registrarVentaACredito = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        miten_consultarDeudaDeCliente = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        miten_registrarPagoDelCliente = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        miten_reporteDeVentaACredito = new javax.swing.JMenuItem();
        menu_proveedor = new javax.swing.JMenu();
        miten_registrarProveedor = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        miten_registrarDeudaAProveedor = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        miten_consultarDeudaAProveedor = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        miten_registrarPagoAProveedor = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        miten_reporteDeDeudaAProveedor = new javax.swing.JMenuItem();
        menu_utilitarios = new javax.swing.JMenu();
        miten_liquid = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        miten_metal = new javax.swing.JMenuItem();
        menu_salir = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta SVMA");

        lbl_hora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_hora.setText("Hora:");

        lbl_data.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_data.setText("Fecha:");

        lbl_logo.setBackground(new java.awt.Color(51, 255, 255));
        lbl_logo.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\Comercial Esplendi.jpg")); // NOI18N

        menu_producto.setMnemonic('P');
        menu_producto.setText("Producto");
        menu_producto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miten_registrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_registrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_registrar.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\estar.png")); // NOI18N
        miten_registrar.setText("Registrar");
        miten_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_registrarActionPerformed(evt);
            }
        });
        menu_producto.add(miten_registrar);
        menu_producto.add(jSeparator1);

        miten_modificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_modificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_modificar.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\refresh.png")); // NOI18N
        miten_modificar.setText("Modificar");
        miten_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_modificarActionPerformed(evt);
            }
        });
        menu_producto.add(miten_modificar);
        menu_producto.add(jSeparator2);

        miten_eliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_eliminar.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\delete.png")); // NOI18N
        miten_eliminar.setText("Eliminar");
        miten_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_eliminarActionPerformed(evt);
            }
        });
        menu_producto.add(miten_eliminar);
        menu_producto.add(jSeparator3);

        miten_consultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_consultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_consultar.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\buscar.png")); // NOI18N
        miten_consultar.setText("Consultar");
        menu_producto.add(miten_consultar);
        menu_producto.add(jSeparator4);

        miten_registrarCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miten_registrarCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_registrarCompra.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\caja-registradora.png")); // NOI18N
        miten_registrarCompra.setText("Registrar Compra");
        miten_registrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_registrarCompraActionPerformed(evt);
            }
        });
        menu_producto.add(miten_registrarCompra);
        menu_producto.add(jSeparator5);

        miten_reporteCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miten_reporteCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_reporteCompra.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\report_key.png")); // NOI18N
        miten_reporteCompra.setText("Reporte Compra");
        menu_producto.add(miten_reporteCompra);

        miten_repProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_repProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_repProducto.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\reporte.png")); // NOI18N
        miten_repProducto.setText("Reporte Producto");
        miten_repProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_repProductoActionPerformed(evt);
            }
        });
        menu_producto.add(miten_repProducto);

        jMenuBar1.add(menu_producto);

        menu_venta.setText("Venta ");
        menu_venta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miten_registrarVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_registrarVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_registrarVenta.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\getmoney.png")); // NOI18N
        miten_registrarVenta.setText("RegistrarVenta");
        miten_registrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_registrarVentaActionPerformed(evt);
            }
        });
        menu_venta.add(miten_registrarVenta);
        menu_venta.add(jSeparator6);

        miten_registrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_registrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_registrarCliente.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\addphoto.png")); // NOI18N
        miten_registrarCliente.setText("Registrar Cliente");
        menu_venta.add(miten_registrarCliente);
        menu_venta.add(jSeparator7);

        miten_reporteVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_reporteVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_reporteVenta.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\money.png")); // NOI18N
        miten_reporteVenta.setText("Reporte Venta");
        miten_reporteVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_reporteVentaActionPerformed(evt);
            }
        });
        menu_venta.add(miten_reporteVenta);

        jMenuBar1.add(menu_venta);

        menu_inventario.setText("Inventario");
        menu_inventario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miten_revisar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_revisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_revisar.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\inventario.jpg")); // NOI18N
        miten_revisar.setText("Revisar");
        menu_inventario.add(miten_revisar);
        menu_inventario.add(jSeparator8);

        miten_prepararPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_prepararPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_prepararPedido.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\prepararPedido.jpg")); // NOI18N
        miten_prepararPedido.setText("Preparar Pedido");
        menu_inventario.add(miten_prepararPedido);

        jMenuBar1.add(menu_inventario);

        menu_cuentacorriente.setText("Cuenta corriente");
        menu_cuentacorriente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miten_registrarVentaACredito.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_registrarVentaACredito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_registrarVentaACredito.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\compras.png")); // NOI18N
        miten_registrarVentaACredito.setText("Registrar venta a crédito");
        menu_cuentacorriente.add(miten_registrarVentaACredito);
        menu_cuentacorriente.add(jSeparator9);

        miten_consultarDeudaDeCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_consultarDeudaDeCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_consultarDeudaDeCliente.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\revisar.png")); // NOI18N
        miten_consultarDeudaDeCliente.setText("Consultar deuda de cliente");
        menu_cuentacorriente.add(miten_consultarDeudaDeCliente);
        menu_cuentacorriente.add(jSeparator10);

        miten_registrarPagoDelCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_registrarPagoDelCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_registrarPagoDelCliente.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\removephoto.png")); // NOI18N
        miten_registrarPagoDelCliente.setText("Registrar pago del cliente");
        miten_registrarPagoDelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_registrarPagoDelClienteActionPerformed(evt);
            }
        });
        menu_cuentacorriente.add(miten_registrarPagoDelCliente);
        menu_cuentacorriente.add(jSeparator11);

        miten_reporteDeVentaACredito.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_reporteDeVentaACredito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_reporteDeVentaACredito.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\analitica (1).png")); // NOI18N
        miten_reporteDeVentaACredito.setText("Reporte de venta a crédito");
        miten_reporteDeVentaACredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_reporteDeVentaACreditoActionPerformed(evt);
            }
        });
        menu_cuentacorriente.add(miten_reporteDeVentaACredito);

        jMenuBar1.add(menu_cuentacorriente);

        menu_proveedor.setText("Proveedor ");
        menu_proveedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miten_registrarProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_registrarProveedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_registrarProveedor.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\user-32.png")); // NOI18N
        miten_registrarProveedor.setText("Registrar proveedor");
        miten_registrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_registrarProveedorActionPerformed(evt);
            }
        });
        menu_proveedor.add(miten_registrarProveedor);
        menu_proveedor.add(jSeparator12);

        miten_registrarDeudaAProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_registrarDeudaAProveedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_registrarDeudaAProveedor.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\deuda.png")); // NOI18N
        miten_registrarDeudaAProveedor.setText("Registrar deuda a proveedor");
        menu_proveedor.add(miten_registrarDeudaAProveedor);
        menu_proveedor.add(jSeparator13);

        miten_consultarDeudaAProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_consultarDeudaAProveedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_consultarDeudaAProveedor.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\consulta.png")); // NOI18N
        miten_consultarDeudaAProveedor.setText("Consultar deuda a proveedor");
        menu_proveedor.add(miten_consultarDeudaAProveedor);
        menu_proveedor.add(jSeparator14);

        miten_registrarPagoAProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miten_registrarPagoAProveedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_registrarPagoAProveedor.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\metodo-de-pago.png")); // NOI18N
        miten_registrarPagoAProveedor.setText("Registrar pago a proveedor");
        menu_proveedor.add(miten_registrarPagoAProveedor);
        menu_proveedor.add(jSeparator15);

        miten_reporteDeDeudaAProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_reporteDeDeudaAProveedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_reporteDeDeudaAProveedor.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\reporte.png")); // NOI18N
        miten_reporteDeDeudaAProveedor.setText("Reporte de deuda a proveedor");
        menu_proveedor.add(miten_reporteDeDeudaAProveedor);

        jMenuBar1.add(menu_proveedor);

        menu_utilitarios.setMnemonic('U');
        menu_utilitarios.setText("Utilitarios ");
        menu_utilitarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miten_liquid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_liquid.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\application_double.png")); // NOI18N
        miten_liquid.setText("Look And Feel -Liquid");
        miten_liquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_liquidActionPerformed(evt);
            }
        });
        menu_utilitarios.add(miten_liquid);
        menu_utilitarios.add(jSeparator16);

        miten_metal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miten_metal.setIcon(new javax.swing.ImageIcon("C:\\SVMA\\svma\\graficos\\table.png")); // NOI18N
        miten_metal.setText("Look And Feel -Metal");
        miten_metal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_metalActionPerformed(evt);
            }
        });
        menu_utilitarios.add(miten_metal);

        jMenuBar1.add(menu_utilitarios);

        menu_salir.setMnemonic('S');
        menu_salir.setText("Salir");
        menu_salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_salirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_data)
                            .addComponent(lbl_hora)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbl_logo)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lbl_logo)
                .addGap(28, 28, 28)
                .addComponent(lbl_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_hora)
                .addContainerGap())
        );

        setBounds(0, 0, 630, 441);
    }// </editor-fold>//GEN-END:initComponents

    private void miten_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_registrarActionPerformed

    private void miten_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_modificarActionPerformed

    private void miten_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_eliminarActionPerformed

    private void miten_registrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_registrarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_registrarVentaActionPerformed

    private void miten_registrarPagoDelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_registrarPagoDelClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_registrarPagoDelClienteActionPerformed

    private void miten_reporteVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_reporteVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_reporteVentaActionPerformed

    private void miten_registrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_registrarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_registrarProveedorActionPerformed

    private void miten_reporteDeVentaACreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_reporteDeVentaACreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_reporteDeVentaACreditoActionPerformed

    private void miten_registrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_registrarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miten_registrarCompraActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
        mostrar_datos.leer_hora();
        lbl_hora.setText("Hora actual: "+mostrar_datos.hora);
    }//GEN-LAST:event_timer1OnTime

    private void menu_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_salirMouseClicked

    private void miten_liquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_liquidActionPerformed
        // TODO add your handling code here:
        set_look = "com.birosoft.liquid.LiquidLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_miten_liquidActionPerformed

    private void miten_metalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_metalActionPerformed
        // TODO add your handling code here:
        set_look = "javax.swing.plaf.metal.MetalLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_miten_metalActionPerformed

    private void miten_repProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_repProductoActionPerformed
        // TODO add your handling code here:
        try{
            //Declaración de las variables
            Connection conn = null;  
            conn =  Conexion.getConnection();
           JasperReport reporte= null;
           String path= "C:\\SVMA\\svma\\src\\py\\com\\svma\\reportes\\reporteProductos.jrxml";
           
           reporte= JasperCompileManager.compileReport(path);
           JasperPrint jprint= JasperFillManager.fillReport(reporte, null,conn);
               
           JasperViewer view=new JasperViewer(jprint, false);
           //view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
           view.setVisible(true);
    }                                                     
      catch(JRException ex){
       System.out.println("Excepcion en reporte");
    }   catch (SQLException ex) {    
            java.util.logging.Logger.getLogger(VentanaPrincipalSVMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }    
        
    }//GEN-LAST:event_miten_repProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalSVMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalSVMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalSVMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalSVMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//
    //Utilizamos el tipo interface como referencia
        //a una clase concreta
        ProductoDAO productoDao = new ProductoDaoJDBC();
        /**Creamos un nuevo registro
        *Hacemos uso de la clase producto DTO la cual se usa
        *para transferir la información entre las capas
        *no es necesario especificar la llave primaria
        *ya que en este caso es de tipo autonumerico y la BD se encarga
        *de asignarle un nuevo valor*/
        ProductoDTO producto = new ProductoDTO();
        producto.setId_producto(95354);
        producto.setDescripcion("Agua Gasificada");
        producto.setCod_unidad(3);
        producto.setStockActual(40);
        producto.setStockMinimo(10);
        producto.setPrecio(2500);

        //Utilizamos la capa DAO para persistir el objeto DTO
        try {
        //productoDao.insert(producto);
        //eliminamos un registro, el id 95354
        //productoDao.delete( new ProductoDTO(95354));
        //actualizamos un campo
        ProductoDTO productoTmp= new ProductoDTO();
        productoTmp.setId_producto(12346);//actualizamos el  campo  registro 12346
        productoTmp.setStockActual(20);
        productoDao.update(productoTmp);
        //Seleccionamos todos los registros
        List<ProductoDTO> productos = productoDao.select();
        for (ProductoDTO productoDTO : productos) {
        System.out.print( productoDTO );
        System.out.println();
        }
        } catch (SQLException e) {
        System.out.println("Excepcion en la capa de prueba");
        e.printStackTrace();
        }
//
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalSVMA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JMenu menu_cuentacorriente;
    private javax.swing.JMenu menu_inventario;
    private javax.swing.JMenu menu_producto;
    private javax.swing.JMenu menu_proveedor;
    private javax.swing.JMenu menu_salir;
    private javax.swing.JMenu menu_utilitarios;
    private javax.swing.JMenu menu_venta;
    private javax.swing.JMenuItem miten_consultar;
    private javax.swing.JMenuItem miten_consultarDeudaAProveedor;
    private javax.swing.JMenuItem miten_consultarDeudaDeCliente;
    private javax.swing.JMenuItem miten_eliminar;
    private javax.swing.JMenuItem miten_liquid;
    private javax.swing.JMenuItem miten_metal;
    private javax.swing.JMenuItem miten_modificar;
    private javax.swing.JMenuItem miten_prepararPedido;
    private javax.swing.JMenuItem miten_registrar;
    private javax.swing.JMenuItem miten_registrarCliente;
    private javax.swing.JMenuItem miten_registrarCompra;
    private javax.swing.JMenuItem miten_registrarDeudaAProveedor;
    private javax.swing.JMenuItem miten_registrarPagoAProveedor;
    private javax.swing.JMenuItem miten_registrarPagoDelCliente;
    private javax.swing.JMenuItem miten_registrarProveedor;
    private javax.swing.JMenuItem miten_registrarVenta;
    private javax.swing.JMenuItem miten_registrarVentaACredito;
    private javax.swing.JMenuItem miten_repProducto;
    private javax.swing.JMenuItem miten_reporteCompra;
    private javax.swing.JMenuItem miten_reporteDeDeudaAProveedor;
    private javax.swing.JMenuItem miten_reporteDeVentaACredito;
    private javax.swing.JMenuItem miten_reporteVenta;
    private javax.swing.JMenuItem miten_revisar;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables


public void lookandfeel()
{
try
{
//La variable set look tiene que estar definida arriba como una variable String
UIManager.setLookAndFeel(set_look);
SwingUtilities.updateComponentTreeUI(this);
}
catch (Exception error)
{
JOptionPane.showMessageDialog(null, error);
}
}

}
